on: [push, pull_request]
jobs:
  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.scheme }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.3, 11.3.1, 11.4]
        scheme: [Tentacle-OSX, Tentacle-iOS]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          nestedSubmodules: true
      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - run: script/cibuild Tentacle.xcworkspace ${{ matrix.scheme }} "build-for-testing test-without-building"

  update-test-fixtures:
    name: Update Test Fixtures
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.4]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          nestedSubmodules: true
      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - run: script/cibuild Tentacle.xcworkspace update-test-fixtures build

  swiftpm-darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.4]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          nestedSubmodules: false
      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - name: Cache built Swift Package artifacts
        uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-Xcode-${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-Xcode-${{ matrix.xcode }}-spm-
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
